export const actions = {
    LOADING_DASHBOARD_MOVIES: 'LOADING_DASHBOARD_MOVIES',
    LOADING_DASHBOARD_THEATERS: 'LOADING_DASHBOARD_THEATERS',
    LOADING_DASHBOARD_ORDERS: 'LOADING_DASHBOARD_ORDERS',
    LOADING_CHARTS: 'LOADING_CHARTS',
    LOADING_THEATER_CHOICES: 'LOADING_THEATER_CHOICES',

    SET_DASHBOARD_MOVIES: 'SET_DASHBOARD_MOVIES',
    SET_DASHBOARD_THEATERS: 'SET_DASHBOARD_THEATERS',
    SET_DASHBOARD_ORDERS: 'SET_DASHBOARD_ORDERS',
    SET_CHARTS: 'SET_CHARTS',
    SET_THEATER_CHOICES: 'SET_THEATER_CHOICES',
}