export const actions = {
    LOADING_THEATERS: 'LOADING_THEATERS',
    SET_THEATERS: 'SET_THEATERS',

    LOADING_SHOW_TIMES: 'LOADING_SHOW_TIMES',
    SET_SHOW_TIMES: 'SET_SHOW_TIMES',

    LOADING_THEATER_STATUS_CHOICES: 'LOADING_THEATER_STATUS_CHOICES',
    SET_THEATER_STATUS_CHOICES: 'SET_THEATER_STATUS_CHOICES'
}