export const actions = {
    LOADING_ORDERS: 'LOADING_ORDERS',
    SET_ORDERS: 'SET_ORDERS',

    LOADING_ORDER_STATUS_CHOICES: 'LOADING_ORDER_STATUS_CHOICES',
    SET_ORDER_STATUS_CHOICES: 'SET_ORDER_STATUS_CHOICES'
}