export const actions = {
    LOADING_TICKETS: 'LOADING_TICKETS',
    SET_TICKETS: 'SET_TICKETS',

    LOADING_TICKET_STATUS_CHOICES: 'LOADING_TICKET_STATUS_CHOICES',
    SET_TICKET_STATUS_CHOICES: 'SET_TICKET_STATUS_CHOICES'
}